name: train nlu and ner models

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Deploy runner on EC2
        shell: bash
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-east \
          --cloud-type g5.xlarge \
          --cloud-spot true \
          --cloud-spot-price 1.123 \
          --labels cml-gpu \
          --idle-timeout 60 \
          --reuse-idle \
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted, cml-gpu]
    timeout-minutes: 1440 # One day
    container:
      image: iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.9'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install make python3-pip virtualenv libpq-dev
    - name: setup-repo
      run: |

        cml ci
    - name: create-report-md
      run: echo "## Metrics" > report.md
    - name: make-report-comment
      run: cml comment create --pr report.md
